name: FNO Bot
on:
  schedule:
    - cron: '*/15 3-10 * * 1-5'
  workflow_dispatch:
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - run: pip install yfinance pandas requests pytz
      - run: python bot.py
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
